# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\tools\zootools\zoo\apps\skinwrangler\skinwrangler.ui'
#
# Created: Wed Feb 01 21:14:43 2017
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from qt import QtCore, QtGui, QtWidgets


class Ui_skinWranglerDlg(object):
    def setupUi(self, skinWranglerDlg):
        self.verticalLayout = QtWidgets.QVBoxLayout(skinWranglerDlg)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(skinWranglerDlg)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.msh = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.msh.setFont(font)
        self.msh.setObjectName("msh")
        self.gridLayout_2.addWidget(self.msh, 0, 0, 1, 1)
        self.skn = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.skn.setFont(font)
        self.skn.setObjectName("skn")
        self.gridLayout_2.addWidget(self.skn, 0, 2, 1, 1)
        self.vtx = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.vtx.setFont(font)
        self.vtx.setObjectName("vtx")
        self.gridLayout_2.addWidget(self.vtx, 0, 4, 1, 1)
        self.mshLBL = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.mshLBL.setFont(font)
        self.mshLBL.setObjectName("mshLBL")
        self.gridLayout_2.addWidget(self.mshLBL, 1, 0, 1, 1)
        self.sknLBL = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.sknLBL.setFont(font)
        self.sknLBL.setObjectName("sknLBL")
        self.gridLayout_2.addWidget(self.sknLBL, 1, 2, 1, 1)
        self.vtxLBL = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.vtxLBL.setFont(font)
        self.vtxLBL.setObjectName("vtxLBL")
        self.gridLayout_2.addWidget(self.vtxLBL, 1, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selGrowBTN = QtWidgets.QPushButton(self.groupBox)
        self.selGrowBTN.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.selGrowBTN.setFont(font)
        self.selGrowBTN.setObjectName("selGrowBTN")
        self.horizontalLayout.addWidget(self.selGrowBTN)
        self.selShrinkBTN = QtWidgets.QPushButton(self.groupBox)
        self.selShrinkBTN.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.selShrinkBTN.setFont(font)
        self.selShrinkBTN.setObjectName("selShrinkBTN")
        self.horizontalLayout.addWidget(self.selShrinkBTN)
        self.selShellBTN = QtWidgets.QPushButton(self.groupBox)
        self.selShellBTN.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.selShellBTN.setFont(font)
        self.selShellBTN.setObjectName("selShellBTN")
        self.horizontalLayout.addWidget(self.selShellBTN)
        self.selLoopBTN = QtWidgets.QPushButton(self.groupBox)
        self.selLoopBTN.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.selLoopBTN.setFont(font)
        self.selLoopBTN.setObjectName("selLoopBTN")
        self.horizontalLayout.addWidget(self.selLoopBTN)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.selPointsEffectedBTN = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.selPointsEffectedBTN.setFont(font)
        self.selPointsEffectedBTN.setObjectName("selPointsEffectedBTN")
        self.verticalLayout_2.addWidget(self.selPointsEffectedBTN)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(skinWranglerDlg)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 6, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.skinMaxInfLBL = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.skinMaxInfLBL.setFont(font)
        self.skinMaxInfLBL.setObjectName("skinMaxInfLBL")
        self.gridLayout_3.addWidget(self.skinMaxInfLBL, 0, 7, 1, 1)
        self.skinAlgoLBL = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.skinAlgoLBL.setFont(font)
        self.skinAlgoLBL.setObjectName("skinAlgoLBL")
        self.gridLayout_3.addWidget(self.skinAlgoLBL, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 5, 1, 1)
        self.skinNormalCMB = QtWidgets.QComboBox(self.groupBox_2)
        self.skinNormalCMB.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.skinNormalCMB.setFont(font)
        self.skinNormalCMB.setObjectName("skinNormalCMB")
        self.skinNormalCMB.addItem("")
        self.skinNormalCMB.addItem("")
        self.skinNormalCMB.addItem("")
        self.gridLayout_3.addWidget(self.skinNormalCMB, 0, 4, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.weightZeroBTN = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.weightZeroBTN.setFont(font)
        self.weightZeroBTN.setObjectName("weightZeroBTN")
        self.horizontalLayout_2.addWidget(self.weightZeroBTN)
        self.weightHalfBTN = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.weightHalfBTN.setFont(font)
        self.weightHalfBTN.setObjectName("weightHalfBTN")
        self.horizontalLayout_2.addWidget(self.weightHalfBTN)
        self.weightFullBTN = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.weightFullBTN.setFont(font)
        self.weightFullBTN.setObjectName("weightFullBTN")
        self.horizontalLayout_2.addWidget(self.weightFullBTN)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.setWeightBTN = QtWidgets.QPushButton(self.groupBox_2)
        self.setWeightBTN.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.setWeightBTN.setFont(font)
        self.setWeightBTN.setObjectName("setWeightBTN")
        self.gridLayout.addWidget(self.setWeightBTN, 0, 0, 1, 1)
        self.plusWeightBTN = QtWidgets.QPushButton(self.groupBox_2)
        self.plusWeightBTN.setMaximumSize(QtCore.QSize(25, 16777215))
        self.plusWeightBTN.setObjectName("plusWeightBTN")
        self.gridLayout.addWidget(self.plusWeightBTN, 0, 3, 1, 1)
        self.minusWeightBTN = QtWidgets.QPushButton(self.groupBox_2)
        self.minusWeightBTN.setMaximumSize(QtCore.QSize(25, 16777215))
        self.minusWeightBTN.setObjectName("minusWeightBTN")
        self.gridLayout.addWidget(self.minusWeightBTN, 0, 4, 1, 1)
        self.setWeightSpin = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.setWeightSpin.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.setWeightSpin.setFont(font)
        self.setWeightSpin.setSingleStep(0.01)
        self.setWeightSpin.setProperty("value", 0.1)
        self.setWeightSpin.setObjectName("setWeightSpin")
        self.gridLayout.addWidget(self.setWeightSpin, 0, 2, 1, 1)
        self.scaleWeightBTN = QtWidgets.QPushButton(self.groupBox_2)
        self.scaleWeightBTN.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.scaleWeightBTN.setFont(font)
        self.scaleWeightBTN.setObjectName("scaleWeightBTN")
        self.gridLayout.addWidget(self.scaleWeightBTN, 1, 0, 1, 1)
        self.scaleWeightSpin = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.scaleWeightSpin.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.scaleWeightSpin.setFont(font)
        self.scaleWeightSpin.setSingleStep(0.01)
        self.scaleWeightSpin.setProperty("value", 0.1)
        self.scaleWeightSpin.setObjectName("scaleWeightSpin")
        self.gridLayout.addWidget(self.scaleWeightSpin, 1, 2, 1, 1)
        self.multWeightBTN = QtWidgets.QPushButton(self.groupBox_2)
        self.multWeightBTN.setEnabled(False)
        self.multWeightBTN.setMaximumSize(QtCore.QSize(25, 16777215))
        self.multWeightBTN.setObjectName("multWeightBTN")
        self.gridLayout.addWidget(self.multWeightBTN, 1, 3, 1, 1)
        self.pasteBTN = QtWidgets.QPushButton(self.groupBox_2)
        self.pasteBTN.setEnabled(True)
        self.pasteBTN.setMinimumSize(QtCore.QSize(0, 0))
        self.pasteBTN.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.pasteBTN.setFont(font)
        self.pasteBTN.setObjectName("pasteBTN")
        self.gridLayout.addWidget(self.pasteBTN, 2, 2, 1, 1)
        self.refreshBTN = QtWidgets.QPushButton(self.groupBox_2)
        self.refreshBTN.setMaximumSize(QtCore.QSize(25, 16777215))
        self.refreshBTN.setObjectName("refreshBTN")
        self.gridLayout.addWidget(self.refreshBTN, 2, 4, 1, 1)
        self.divWeightBTN = QtWidgets.QPushButton(self.groupBox_2)
        self.divWeightBTN.setEnabled(False)
        self.divWeightBTN.setMaximumSize(QtCore.QSize(25, 16777215))
        self.divWeightBTN.setObjectName("divWeightBTN")
        self.gridLayout.addWidget(self.divWeightBTN, 1, 4, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.setAverageWeightBTN = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.setAverageWeightBTN.setFont(font)
        self.setAverageWeightBTN.setObjectName("setAverageWeightBTN")
        self.horizontalLayout_8.addWidget(self.setAverageWeightBTN)
        self.copyBTN = QtWidgets.QPushButton(self.groupBox_2)
        self.copyBTN.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.copyBTN.setFont(font)
        self.copyBTN.setCheckable(True)
        self.copyBTN.setObjectName("copyBTN")
        self.horizontalLayout_8.addWidget(self.copyBTN)
        self.gridLayout.addLayout(self.horizontalLayout_8, 2, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.filterBTN = QtWidgets.QPushButton(self.groupBox_2)
        self.filterBTN.setMaximumSize(QtCore.QSize(55, 20))
        self.filterBTN.setObjectName("filterBTN")
        self.horizontalLayout_6.addWidget(self.filterBTN)
        self.filterLINE = QtWidgets.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.filterLINE.setFont(font)
        self.filterLINE.setObjectName("filterLINE")
        self.horizontalLayout_6.addWidget(self.filterLINE)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.jointLST = QtWidgets.QTreeWidget(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.jointLST.setFont(font)
        self.jointLST.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.jointLST.setIconSize(QtCore.QSize(20, 20))
        self.jointLST.setRootIsDecorated(False)
        self.jointLST.setItemsExpandable(False)
        self.jointLST.setColumnCount(2)
        self.jointLST.setObjectName("jointLST")
        self.jointLST.headerItem().setText(0, "JOINT")
        item_0 = QtWidgets.QTreeWidgetItem(self.jointLST)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.jointLST.header().setVisible(True)
        self.jointLST.header().setDefaultSectionSize(120)
        self.verticalLayout_3.addWidget(self.jointLST)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.listAllCHK = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.listAllCHK.setFont(font)
        self.listAllCHK.setChecked(True)
        self.listAllCHK.setObjectName("listAllCHK")
        self.horizontalLayout_4.addWidget(self.listAllCHK)
        self.nameSpaceCHK = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.nameSpaceCHK.setFont(font)
        self.nameSpaceCHK.setChecked(True)
        self.nameSpaceCHK.setObjectName("nameSpaceCHK")
        self.horizontalLayout_4.addWidget(self.nameSpaceCHK)
        self.longNamesCHK = QtWidgets.QCheckBox(self.groupBox_2)
        self.longNamesCHK.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.longNamesCHK.setFont(font)
        self.longNamesCHK.setObjectName("longNamesCHK")
        self.horizontalLayout_4.addWidget(self.longNamesCHK)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.dynAnnotationCHK = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dynAnnotationCHK.setFont(font)
        self.dynAnnotationCHK.setChecked(False)
        self.dynAnnotationCHK.setObjectName("dynAnnotationCHK")
        self.horizontalLayout_10.addWidget(self.dynAnnotationCHK)
        self.labelJointsCHK = QtWidgets.QCheckBox(self.groupBox_2)
        self.labelJointsCHK.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelJointsCHK.setFont(font)
        self.labelJointsCHK.setObjectName("labelJointsCHK")
        self.horizontalLayout_10.addWidget(self.labelJointsCHK)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.tabWidget = QtWidgets.QTabWidget(skinWranglerDlg)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 85))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.removeUnusedBTN = QtWidgets.QPushButton(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.removeUnusedBTN.setFont(font)
        self.removeUnusedBTN.setObjectName("removeUnusedBTN")
        self.horizontalLayout_5.addWidget(self.removeUnusedBTN)
        self.clampInfBTN = QtWidgets.QPushButton(self.tab_3)
        self.clampInfBTN.setMaximumSize(QtCore.QSize(122, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.clampInfBTN.setFont(font)
        self.clampInfBTN.setObjectName("clampInfBTN")
        self.horizontalLayout_5.addWidget(self.clampInfBTN)
        self.clampInfSPIN = QtWidgets.QSpinBox(self.tab_3)
        self.clampInfSPIN.setMaximumSize(QtCore.QSize(33, 16777215))
        self.clampInfSPIN.setProperty("value", 4)
        self.clampInfSPIN.setObjectName("clampInfSPIN")
        self.horizontalLayout_5.addWidget(self.clampInfSPIN)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.addJntBTN = QtWidgets.QPushButton(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.addJntBTN.setFont(font)
        self.addJntBTN.setObjectName("addJntBTN")
        self.horizontalLayout_7.addWidget(self.addJntBTN)
        self.bindPoseBTN = QtWidgets.QPushButton(self.tab_3)
        self.bindPoseBTN.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.bindPoseBTN.setFont(font)
        self.bindPoseBTN.setObjectName("bindPoseBTN")
        self.horizontalLayout_7.addWidget(self.bindPoseBTN)
        self.selectVertsWithInfBTN = QtWidgets.QPushButton(self.tab_3)
        self.selectVertsWithInfBTN.setMaximumSize(QtCore.QSize(131, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.selectVertsWithInfBTN.setFont(font)
        self.selectVertsWithInfBTN.setObjectName("selectVertsWithInfBTN")
        self.horizontalLayout_7.addWidget(self.selectVertsWithInfBTN)
        self.selectVertsWithInfSPIN = QtWidgets.QSpinBox(self.tab_3)
        self.selectVertsWithInfSPIN.setMaximumSize(QtCore.QSize(57, 16777215))
        self.selectVertsWithInfSPIN.setProperty("value", 4)
        self.selectVertsWithInfSPIN.setObjectName("selectVertsWithInfSPIN")
        self.horizontalLayout_7.addWidget(self.selectVertsWithInfSPIN)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.jointOnBboxCenterBTN = QtWidgets.QPushButton(self.tab_4)
        self.jointOnBboxCenterBTN.setGeometry(QtCore.QRect(0, 0, 196, 23))
        self.jointOnBboxCenterBTN.setCheckable(True)
        self.jointOnBboxCenterBTN.setObjectName("jointOnBboxCenterBTN")
        self.avgOptionCHK = QtWidgets.QCheckBox(self.tab_4)
        self.avgOptionCHK.setGeometry(QtCore.QRect(0, 30, 336, 15))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.avgOptionCHK.setFont(font)
        self.avgOptionCHK.setObjectName("avgOptionCHK")
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(skinWranglerDlg)
        self.tabWidget.setCurrentIndex(0)
        self.copyBTN.clicked.connect(self.pasteBTN.toggle)
        QtCore.QMetaObject.connectSlotsByName(skinWranglerDlg)

    def retranslateUi(self, skinWranglerDlg):
        skinWranglerDlg.setWindowTitle("skinWrangler")
        self.groupBox.setTitle("VERT SELECTION")
        self.msh.setText("MSH:")
        self.skn.setText("SKN:")
        self.vtx.setText("VTX:")
        self.mshLBL.setText("None")
        self.sknLBL.setText("None")
        self.vtxLBL.setText("None")
        self.selGrowBTN.setText("GROW")
        self.selShrinkBTN.setText("SHRINK")
        self.selShellBTN.setText("SHELL")
        self.selLoopBTN.setText("LOOP")
        self.selPointsEffectedBTN.setText("VERTS EFFECTED BY SELECTED JOINTS")
        self.groupBox_2.setTitle("SKINNING")
        self.label_2.setText("NORMALIZATION:  ")
        self.label_3.setText("MAX INF:  ")
        self.label_4.setText("SKIN:  ")
        self.skinMaxInfLBL.setText("None")
        self.skinAlgoLBL.setText("None")
        self.skinNormalCMB.setItemText(0, "None")
        self.skinNormalCMB.setItemText(1, "Interactive")
        self.skinNormalCMB.setItemText(2, "Post")
        self.weightZeroBTN.setText("0.0")
        self.weightHalfBTN.setText("0.5")
        self.weightFullBTN.setText("1.0")
        self.setWeightBTN.setToolTip("Explicitely set the weight value")
        self.setWeightBTN.setText("SET WEIGHT")
        self.plusWeightBTN.setToolTip("Add value to current weight for selected joint")
        self.plusWeightBTN.setText("+")
        self.minusWeightBTN.setToolTip("Subtract value to current weight for selected joint")
        self.minusWeightBTN.setText("-")
        self.scaleWeightBTN.setText("SCALE WEIGHT")
        self.multWeightBTN.setText("*")
        self.pasteBTN.setToolTip("Paste stored skinning weights")
        self.pasteBTN.setText("PASTE")
        self.refreshBTN.setToolTip("Used to refresh the weight list")
        self.refreshBTN.setText("<")
        self.divWeightBTN.setText("/")
        self.setAverageWeightBTN.setText("AVERAGE")
        self.copyBTN.setToolTip("Copy/store skinning info for current selection")
        self.copyBTN.setText("COPY")
        self.label.setText("JOINT INFLUENCE LIST:")
        self.filterBTN.setText("FILTER")
        self.jointLST.headerItem().setText(0, "AVG WEIGHT")
        self.jointLST.setSortingEnabled(False)
        self.jointLST.topLevelItem(0).setText(0, "joint01")
        self.jointLST.setSortingEnabled(self.jointLST.isSortingEnabled())
        self.listAllCHK.setText("List all influences")
        self.nameSpaceCHK.setText("strip nameSpace")
        self.longNamesCHK.setText("longNames")
        self.dynAnnotationCHK.setText("Dynamic annotation")
        self.labelJointsCHK.setText("Label joints")
        self.removeUnusedBTN.setToolTip("Maya remove unused influences command")
        self.removeUnusedBTN.setText("REMOVE UNUSED INFS")
        self.clampInfBTN.setToolTip("Trims down the smallest values and re-normalizes")
        self.clampInfBTN.setText("CLAMP MAX INFS")
        self.addJntBTN.setText("ADD JNT")
        self.bindPoseBTN.setText("BIND POSE")
        self.selectVertsWithInfBTN.setToolTip("Select vertices that have more influences than the number")
        self.selectVertsWithInfBTN.setText("SEL VTX WITH >")
        self.selectVertsWithInfSPIN.setSuffix(" INF")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), "SKIN CLUSTER UTILS")
        self.jointOnBboxCenterBTN.setText("MAKE JOINT ON BBOX CENTER")
        self.avgOptionCHK.setToolTip("Uses custom code to average skinning,\n respecting the max influences")
        self.avgOptionCHK.setText("Calc \'AVERAGE\' with max inf (no hammer)")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), "TOOLBOX")
